### ISSUE TITLE
Give a warning if the tag in particular is deprecated or no longer supported

### ISSUE THREAD

**Issue by JoshuaHess** [joshbuchea/HEAD#104]
This is a great list, however, a lot of the meta tags listed are tags that aren't supported by many popular search engines anymore, along with other tags in the list. Perhaps just a note to the side saying either supported or not supported/deprecated.

**Comment by joshbuchea** [comment]
@JoshuaHess did your PR #105 satisfy this issue? Or are there still other elements that need notes/comments?

**Comment by JoshuaHess** [comment]
@jochbuchea I can work tonight on fixing the meta tags to show which ones are deprecated, but there are link tags and all sorts of others on the list that aren't normally used or have been abandoned over time.

**Comment by joshbuchea** [comment]
Ok, we'll keep this open then.

**Comment by TraderStf** [comment]
http://www.sitepronews.com/2016/06/01/google-revives-meta-content-with-longer-characters/

**Comment by joshbuchea** [comment]
Closing as this is and will be an ongoing effort.
