### ISSUE TITLE
Translation - Brazilian Portuguese

### ISSUE THREAD

**Issue by suissa** [joshbuchea/HEAD#106]
Can I PR my translation? https://github.com/Webschool-io/HEAD/tree/pt-BR

**Comment by suissa** [comment]
Merged here https://github.com/Webschool-io/HEAD

**Comment by joshbuchea** [comment]
@suissa apologies for not getting back to you sooner. This is awesome! I'd prefer to keep the maintenance on my project to a minimum so I'm resisting adding any new files for as long as I can. But, I would love to link to this if you'd like to maintain this translation in your own repo. Really hope you're up for that. It would be excellent to have this translation available to the community.
