### ISSUE TITLE
Chrome for android

### ISSUE THREAD

**Issue by jonassalen** [joshbuchea/HEAD#11]
Colour notification bar:
https://developers.google.com/web/updates/2014/11/Support-for-theme-color-in-Chrome-39-for-Android

**Comment by joshbuchea** [comment]
Already added by @SaijoGeorge in this [commit](https://github.com/joshbuchea/HEAD/commit/0ecf786128d958823c5038730386fe1a53f910a9). Thanks @jonassalen!
