### ISSUE TITLE
Split into files

### ISSUE THREAD

**Issue by james2doyle** [joshbuchea/HEAD#115]
This is pretty awesome! I usually end of having a ton a gists with different things in them.

I was wondering if there is any plan to break these out into files? Then the can be pulled directly into a project via their https://raw.githubusercontent.com URL.

I use [a plugin for Sublime Text](http://code.tutsplus.com/articles/introducing-nettuts-fetch--net-23490) that lets me fetch a URL and copy the contents to the current window. This would be a good project to have a bunch of snippets of text for.

For example, if you are only interested in adding the head meta for Apple iOS, then you could just request the contents of that single file/piece.

Is there any interest in that type of workflow for anyone else?

**Comment by joshbuchea** [comment]
I just released an Atom package that has most of the snippets from HEAD: [HTML Head Snippets](https://atom.io/packages/html-head-snippets). But, that's only for Atom and also needs to be maintained separately.

For now, I'm trying to keep the project as one document. I think part of the value of this project is all of the information is available in one place. But, I've considered creating separate files for other reasons, and this is one more reason to consider this approach in the future.

If anyone is interested in creating a plugin for Sublime, I'd be more than happy to add a link to it.

Thanks for the feedback @james2doyle!

**Comment by james2doyle** [comment]
That sounds cool.

I thought about the plugin as well. But it would need to keep parity with the README updates. Which is one of the reasons single files would work nicely.

How about keeping the README but *also* having single files?

**Comment by dodekeract** [comment]
What if we generate the README from the files?

**Comment by marcobiedermann** [comment]
@joshbuchea @james2doyle I am currently working on a plugin for Sublime Text.
Will probably publish it today or tomorrow :)

**Comment by marcobiedermann** [comment]
@joshbuchea @james2doyle
Just published the [Sublime Text snippets plugin](https://github.com/marcobiedermann/sublime-head-snippets).
Will have to wait for the approval and when done, I will ping you!

**Comment by joshbuchea** [comment]
@dodekeract interesting idea. Although, I don't think I'd want to make a simple project complex by introducing a build step.

**Comment by joshbuchea** [comment]
@marcobiedermann awesome man! On it! Definitely ping me when it's approved.

**Comment by joshbuchea** [comment]
@james2doyle I think your suggestion is reasonable, and I see the value in the independent files for pulling in the most up-to-date snippets. Let me think about how best to approach this...

If we add separate files _also_, contributors then have to update two places. Three counting the TOC. Which isn't ideal...

**Comment by ThaDafinser** [comment]
@joshbuchea keep this repo as simple as it is - no builds and no splitting.

Everybody is able to extract/split the information easily out of the `README.md` with just splitting by the headlines....

**Comment by jarrydfillmore** [comment]
:)

**Comment by marcobiedermann** [comment]
My Sublime Text just got [published](https://packagecontrol.io/packages/HTML%20Head%20Snippets)!

**Comment by joshbuchea** [comment]
Awesome @marcobiedermann! Will tweet a link. Thanks again for making this.

**Comment by marcobiedermann** [comment]
@joshbuchea @scottaohara I think we can close this one.

**Comment by scottaohara** [comment]
@marcobiedermann agreed.
