### ISSUE TITLE
Sizes attribute for apple-touch-icon?

### ISSUE THREAD

**Issue by radicalbender** [joshbuchea/HEAD#12]
Is it worth noting that the apple-touch-icon can be defined multiple times for different sizes through either the file name or the `sizes` attribute?

For instance, [Real Favicon Generator](https://realfavicongenerator.net/blog/apple-touch-icon-the-good-the-bad-the-ugly/) spits out icons at 57x57, 60x60, 72x72, 76x76, 114x114, 120x120, 144x144, 152x152, and 180x180 to cover the gamut of iOS icon sizes and outputs the link elements like so:

`<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">`

**Comment by joshbuchea** [comment]
Absolutely! I'll get this added. Thanks @radicalbender!

**Comment by joshbuchea** [comment]
Closing, included in #53. Thanks!
