### ISSUE TITLE
ie = edge

### ISSUE THREAD

**Issue by SteveALee** [joshbuchea/HEAD#121]
How important is

'meta http-equiv="x-ua-compatible" content="ie=edge">'

It sticks out like a sore thumb in the recommended minimum section as is totally browser specific. That is bad in my mind. If there is an issue it should be resolved by the vendor and be temporary.

**Comment by joshbuchea** [comment]
The tag is used in both [H5BP](https://github.com/h5bp/html5-boilerplate) & [Bootstrap](https://github.com/twbs/bootstrap); both projects I respect and look to for guidance when making decisions for HEAD. The tag isn't necessary unless you need to support < IE 11, but I don't plan dropping it until at least one of those two projects do. Thanks for the feedback @SteveALee!

**Comment by SteveALee** [comment]
PS - fantastic resource - thanks

**Comment by joshbuchea** [comment]
Thanks @SteveALee 😊

**Comment by kleinfreund** [comment]
> but I don't plan dropping it until at least one of those two projects do.

@joshbuchea As far as I can tell, Bootstrap dropped the tag (https://github.com/twbs/bootstrap/blob/v4-dev/_includes/header.html). If if both projects still have it, I don’t see a reason for maintaining it in the bare minimum example.
