### ISSUE TITLE
Meta theme-color isn't Android only

### ISSUE THREAD

**Issue by HughIsaacs2** [joshbuchea/HEAD#122]
Meta theme-color isn't limited to Google Android or Chrome. It's supported in Opera and Firefox OS (as the link below will reveal) and it's also supported in the Brave and Vivaldi browsers on desktop and even in the WebView tag in Electron (it was also even used by a dev preview version of Safari for the SVG icon color).

https://developers.google.com/web/fundamentals/design-and-ui/browser-customization/theme-color?hl=en

**Comment by joshbuchea** [comment]
Added to meta section. Thanks @HughIsaacs2!
