### ISSUE TITLE
DNS prefetching

### ISSUE THREAD

**Issue by adityasiwan** [joshbuchea/HEAD#126]
As you mentioned 

> "A list of everything that could go in your head"

.
So, why not include DNS prefetching to it as it is quite an important one.

**Comment by tomlutzenberger** [comment]
Do you have a link to documentation, examples, etc.?

**Comment by marcobiedermann** [comment]
@adityasiwan This is already included in Line 272!

**Comment by adityasiwan** [comment]
[https://developer.mozilla.org/en-US/docs/Web/HTTP/Controlling_DNS_prefetching](url)
[https://www.chromium.org/developers/design-documents/dns-prefetching](url)

**Comment by adityasiwan** [comment]
`<!-- Prefetching, preloading, prebrowsing -->`
`<link rel="dns-prefetch" href="//example.com/">`
Well, this is for "Forcing lookup of specific hostnames".

Whereas, i am suggesting "Turning on and off prefetching" which can be done using the meta tag.
Check here https://developer.mozilla.org/en-US/docs/Web/HTTP/Controlling_DNS_prefetching

**Comment by adityasiwan** [comment]
Closing as https://github.com/joshbuchea/HEAD/pull/133 is merged

**Comment by noriellecruz** [comment]
It should also be noted that dns prefetching must be place before other tags, I don't see this in the published guide.
