### ISSUE TITLE
<href>s are in suboptimal order

### ISSUE THREAD

**Issue by nilfalse** [joshbuchea/HEAD#128]
I notice that although a **Performance** section at the very bottom states that it is better to have `href` attribute first on any tags, all examples above that section have their `href`s put in different order.

Was that made occasionally? I'm going to create a pull request which would move all `href`s to the first position. Is this OK?

**Comment by joshbuchea** [comment]
@nilfalse thanks for asking first! Excellent attention to detail! However, this is intentional to increase the overall readability of the project. Moving the href to the beginning of tag decreases the ability to quickly determine it's purpose at a glance.

**Comment by joshbuchea** [comment]
See #80
