### ISSUE TITLE
gh-pages: Links open in new tab

### ISSUE THREAD

**Issue by marcobiedermann** [joshbuchea/HEAD#129]
@joshbuchea
I just noticed that all links on http://gethead.info/ open in a new tab.
Clicking through "Table of Contents" feels a bit weird.
That's because of `<base target="_blank">`.
I've created a little JavaScript snippet to open external links in a new tab.
```
var links = document.links;
  length = links.length;

  for (i = 0; i < length; i++) {
     if (links[i].hostname != window.location.hostname) {
         links[i].target = '_blank';
     }
  }
```

If you like to, I could send you a pull request that resolves this issue :)

**Comment by joshbuchea** [comment]
@marcobiedermann nice catch bruh 🙌 That's an awesome UX :laughing: How'd I not catch that one!? Yeah that'd be awesome man!

**Comment by scottaohara** [comment]
heh, yeah, that's a fundamental rule i found out about ```<base>``` is that there's almost no scenario where setting a target attribute on it is a good idea.

**Comment by joshbuchea** [comment]
Would have worked fine if there were no anchor links :) But I have to admit you're right @scottaohara. Every time I've used `<base>` it's come back to bite me in the ass at some point.

**Comment by marcobiedermann** [comment]
`<base>` is actually really useful when working with static HTML files or single page applications like AngularJS. But never set the `target`attribute.
