### ISSUE TITLE
OEmbed

### ISSUE THREAD

**Issue by jasonkarns** [joshbuchea/HEAD#13]
http://oembed.com/

The generic, standard spec for embedding rich data about links without coupling to site specific (Facebook, Twitter, etc)  elements

**Comment by joshbuchea** [comment]
Closing, because I spent a few minutes researching and it wasn't immediately obvious where I would include this. Feel free to re-open @jasonkarns if you'd like to provide an example.

**Comment by jasonkarns** [comment]
Quick examples taken from oembed docs page:

```html
<link rel="alternate" type="application/json+oembed"
  href="http://flickr.com/services/oembed?url=http%3A%2F%2Fflickr.com%2Fphotos%2Fbees%2F2362225867%2F&format=json"
  title="Bacon Lollys oEmbed Profile" />
<link rel="alternate" type="text/xml+oembed"
  href="http://flickr.com/services/oembed?url=http%3A%2F%2Fflickr.com%2Fphotos%2Fbees%2F2362225867%2F&format=xml"
  title="Bacon Lollys oEmbed Profile" />
```

Only one of those is necessary; so we could probably just showcase the json variant.

As a `link`, it could be listed under the Link section. But it is intended to direct one to an oembed file which is used as media embedding/sharing. So it would make sense to list under the Social section as well. Pick one and I'll open a PR.
