### ISSUE TITLE
Does the <title> not come first?

### ISSUE THREAD

**Issue by johnuberbacher** [joshbuchea/HEAD#153]
Think I've heard <title> tags need to come first as per SEO but I may be wrong and this may be outdated knowledge

**Comment by willpower232** [comment]
Alas outdated thanks to peculiarities in IE IIRC. Would be nice to put it first though!

**Comment by scottaohara** [comment]
yeh, there's no real need to have it first, but there are other tags that do need to appear as early as possible (setting a charset for example) to ensure content is rendered properly.
