### ISSUE TITLE
Info on how to contribute to gethead.me on README.md

### ISSUE THREAD

**Issue by karltaylor** [joshbuchea/HEAD#158]
I just noticed there wasn't any info on how to get the project set up, I know it's obvious to some that the branch for the site is within gh-pages which means it's run on Jekyll, but maybe a little bit of information would be useful so people can get started quickly?

**Comment by dakshshah96** [comment]
Yes, I agree with you @karltaylor.

It would be helpful to have some mention of the `gh-pages` branch and the use of Jekyll somewhere in the contribution guide.
