### ISSUE TITLE
Link specifics

### ISSUE THREAD

**Issue by davidpelayo** [joshbuchea/HEAD#166]
[Here](https://github.com/joshbuchea/HEAD#link) there is a typo:

```html
<!-- Refers to a copyright statement that applies to the links context -->
<link rel="copyright" href="copyright.html">
```

The `link` should have the attribute `rel="license"` instead of `copyright`. [More info here](https://www.w3.org/TR/html5/document-metadata.html#attr-link-rel).

**Comment by joshbuchea** [comment]
Looks good 👍  Thanks for contributions @davidpelayo!
