### ISSUE TITLE
WebMentions

### ISSUE THREAD

**Issue by jasonkarns** [joshbuchea/HEAD#17]
https://github.com/converspace/webmention

Webmention is a simple way to automatically notify any URL when you link to it on your site. From the receivers perpective, it's a way to request notification when other sites link to it.

It’s a modern alternative to Pingback and other forms of Linkback.

Note that the latest, most up-to-date specification is located on the IndieWebCamp wiki.

Of course, could add [pingback](http://www.hixie.ch/specs/pingback/pingback) links, too.

**Comment by kylewm** [comment]
The most up-to-date spec for Webmention these days is https://www.w3.org/TR/webmention/ :+1:
