### ISSUE TITLE
OpenSearch

### ISSUE THREAD

**Issue by jasonkarns** [joshbuchea/HEAD#18]
http://www.opensearch.org/Home 

Link to the opensearch xml manifest in the HEAD and this allows browsers to trigger a search on your site directly from their address bar.

That's how this works: 
![image](https://cloud.githubusercontent.com/assets/119972/14727285/61e22bc2-07f7-11e6-815b-9de4323ea83b.png)

**Comment by joshbuchea** [comment]
Looks like this one was already in there. Updated the example to make it a bit more clear. Thanks @jasonkarns!

**Comment by jasonkarns** [comment]
nice! sorry I missed it
