### ISSUE TITLE
Fluid icon

### ISSUE THREAD

**Issue by szepeviktor** [joshbuchea/HEAD#185]
See https://webmasters.stackexchange.com/a/23697

GitHub has it also: 
```html
<link rel="fluid-icon" href="https://github.com/fluidicon.png" title="GitHub">
```

**Comment by joshbuchea** [comment]
🤔 I wasn't familiar with Fluid before this issue. Looking at the project's website and twitter profile, it's difficult to tell if the project is actively maintained. I'm also not sure if Fluid is common/popular enough to warrant including it. I'm going to have to decline, but thank you for your issue and your interest in improving this project.

**Comment by szepeviktor** [comment]
OK.

At least there is as issue on it anybody can find.

**Comment by joshbuchea** [comment]
@szepeviktor exactly 👍 This issue will now serve as a reference. Thanks for your contribution! 🙌
