### ISSUE TITLE
Promote HTTPS

### ISSUE THREAD

**Issue by szepeviktor** [joshbuchea/HEAD#195]
Hello!

Could we change all `http://` to `https://`?

I do proactive website maintenance and do not install non-https websites for years.

**Comment by kanlukasz** [comment]
+1

**Comment by joshbuchea** [comment]
@szepeviktor you know I actually did this a while back but, later reverted because I was concerned I _may_ have made the change too soon. I think now is the perfect time for this though. Let's do it!

**Comment by szepeviktor** [comment]
OK.
