### ISSUE TITLE
rel-me

### ISSUE THREAD

**Issue by jasonkarns** [joshbuchea/HEAD#20]
A subset of the XFN microformat

http://microformats.org/wiki/rel-me

```
<link rel="me" href="mailto:XXX" />
<link rel="me" href="sms:+123456789" />
```

also related: http://microformats.org/wiki/RelMeAuth and http://microformats.org/wiki/web_sign-in

**Comment by joshbuchea** [comment]
All documentation for `rel="me"` indicates it's for hyperlinks. If you can locate a proper reference indicating it's use with the link element, I'd be happy to add this. Thanks @jasonkarns!

**Comment by TraderStf** [comment]
http://www.w3schools.com/tags/att_link_rel.asp, this one is clear
also in w3.org

**Comment by joshbuchea** [comment]
@TraderStr this thread is about `rel="me"`. I don't see `rel="me"` in the documentation you referenced. Also, I don't consider W3Schools to be an authoritative source. Thanks for your comment through!

**Comment by jasonkarns** [comment]
There's nothing specific about `a`. The HTML spec defines both `link` and `a` as "hyperlinks". (Because they both are hypertext links.) Note the terminology used when describing the attributes of `link`: https://html.spec.whatwg.org/multipage/semantics.html#the-link-element

The @rel attribute is documented for both `link` elements and `a` anchors. The definition of `rel` is:

> Relationship between the document containing the hyperlink and the destination resource 

The rel=me standard defines the `me` value for the `rel` attribute. It is not scoped or limited to particular elements, but is applicable to the `rel` attribute in general.

**Comment by TraderStf** [comment]
seems like a huge 'pot':
http://w3c.github.io/html/single-page.html#design-notes-extensibility
http://w3c.github.io/html/single-page.html#link-types-extensions-to-the-predefined-set-of-link-type
http://microformats.org/wiki/existing-rel-values#HTML5_link_type_extensions
http://microformats.org/wiki/rel-faq

**Comment by joshbuchea** [comment]
Excellent points. I'll go ahead and add this 👍 Thanks @jasonkarns!

**Comment by jasonkarns** [comment]
Thanks @joshbuchea for taking on the actual work from my drive-by suggestions :)
