### ISSUE TITLE
<meta http-equiv="set-cookie"> was removed from Chrome

### ISSUE THREAD

**Issue by toshihidetagami** [joshbuchea/HEAD#204]
https://www.chromestatus.com/feature/6170540112871424
https://github.com/whatwg/html/issues/3076

According to the above links, http-equiv="set-cookie" was removed from Chrome and other browsers may follow suit.
Would it be better to remove from this list or mark it as deprecated?

**Comment by joshbuchea** [comment]
Thanks for pointing this out @toshihidetagami. If Chrome removed it already let's go ahead and remove it too. If you want to create a pull request to remove it, I'd happily accept.
