### ISSUE TITLE
Getting Spammed...

### ISSUE THREAD

**Issue by dschmidthawk** [joshbuchea/HEAD#232]
I'm subscribed to your thread, but recently getting spammed from this account.  Any solution in sight?

**Comment by CodePosse** [comment]
It is a bot that is spamming multiple repos.

**Comment by afuno** [comment]
@dschmidthawk 
<img width="324" alt="Снимок экрана 2020-02-18 в 18 53 41" src="https://user-images.githubusercontent.com/2853419/74752617-02884d00-5280-11ea-96d2-f1cbed6aa233.png">

**Comment by dschmidthawk** [comment]
Thanks

**Comment by SilverTee** [comment]
same for me, ty
