### ISSUE TITLE
Add meta name="SKYPE_TOOLBAR"

### ISSUE THREAD

**Issue by pbakondy** [joshbuchea/HEAD#29]
Prevent Skype from Highlighting Phone Numbers

```html
<meta name="SKYPE_TOOLBAR" content="SKYPE_TOOLBAR_PARSER_COMPATIBLE" />
```

See: http://bacsoftwareconsulting.com/blog/index.php/web-development/prevent-skype-from-highlighting-phone-numbers/

**Comment by joshbuchea** [comment]
Found a more accurate description [here](https://wiki.whatwg.org/wiki/MetaExtensions):

> Prevents the Skype browser extension from automatically seeking through the page and replacing telephone numbers (or any number the program's algorithm thinks is a telephone number) with its own custom presentation that allows direct invocation of the Skype program to call the telephone number.

Looks good though 👍 Added. Thanks @pbakondy!
