### ISSUE TITLE
HTML head elements description

### ISSUE THREAD

**Issue by artemgurzhii** [joshbuchea/HEAD#31]
People would like to know where to use each of this elements and why. It would be nice if you added a description for unknown elements

**Comment by Mxxim** [comment]
+1

**Comment by joshbuchea** [comment]
@artemgurzhii A description for unknown elements sounds great! It will require a bit of balance to add additional information without making the document too overwhelming. I've already begun adding additional info to some elements, but feel free to submit a pull request also! Thanks @artemgurzhii!
