### ISSUE TITLE
dns prefetching-preloading-prebrowsing

### ISSUE THREAD

**Issue by dareenzo** [joshbuchea/HEAD#35]
For google chrome they now have these [dns-prefetch](https://css-tricks.com/prefetching-preloading-prebrowsing/) rules to optimize page perf load time, so I'd suggest you check it out and add.

Also I'd suggest adding [app links](http://applinks.org/documentation) and [schema.org](http://schema.org/)

In addition, I had made thing like this before called [seo-fu](https://github.com/dareenzo/seo-fu/blob/master/seo-fu.html). Maybe check it out...

**Comment by joshbuchea** [comment]
Excellent suggestions @dareenzo! I added prefetching, preloading, prebrowsing, and I'll open new issues for [app links](http://applinks.org/documentation) and [schema.org](http://schema.org/).

I checked out your project [seo-fu](https://github.com/dareenzo/seo-fu/blob/master/seo-fu.html). Very cool. You have a lot that I don't have, I'll likely use it as a source when updating this project. Thanks @dareenzo!
