### ISSUE TITLE
schema.org

### ISSUE THREAD

**Issue by joshbuchea** [joshbuchea/HEAD#42]
[schema.org](http://schema.org/)

**Comment by niksmac** [comment]
I am guessing, this will also end up like #110

**Comment by ThaDafinser** [comment]
Adding an example of schema.org is more helpful, since it's getting more and more important

**Comment by marcobiedermann** [comment]
Schema.org tags are really important for your page. But I think they should not be included in the head section.
99% of all Schema.org tags are used in the body markup.
You could add some properties like "author" or "date" to the head but in my opinion this information should appear in the page content.

**Comment by joshbuchea** [comment]
I agree with you @marcobiedermann. It does seem that 99% of Schema.org tags are in the body. I'm closing this for now. However, as always I am willing to discuss this decision.
