### ISSUE TITLE
Few more

### ISSUE THREAD

**Issue by TraderStf** [joshbuchea/HEAD#45]
sorry, did not clean some known types

https://wiki.whatwg.org/wiki/MetaExtensions

https://en.wikipedia.org/wiki/Microformat
https://en.wikipedia.org/wiki/RDFa
http://ogp.me/#
https://en.wikipedia.org/wiki/Microdata_(HTML)

https://foolip.org/microdatajs/live/
https://validator.nu

https://en.wikipedia.org/wiki/Semantic_Web
https://en.wikipedia.org/wiki/Semantic_HTML

http://www.w3.org/TR/html5/
http://www.w3.org/TR/html5/document-metadata.html#the-meta-element

https://developers.google.com/structured-data/?rd=1

**Comment by TraderStf** [comment]
<link rel="publisher" href="http://plus.google.com/+THEgooglePLUSname" />
http://www.vervesearch.com/blog/how-to-implement-the-relpublisher-google-authorship-mark-up/

Also

http://applinks.org/documentation/
Cross-platform, open source, and simple mobile deep-linking

**Comment by TraderStf** [comment]
What you got on twitter if you redirect to handheld device (link inside normal view (not handheld)).

`<?xml version="1.0" encoding="utf-8"?>`
`<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.1//EN" "http://www.openmobilealliance.org/tech/DTD/xhtml-mobile11.dtd">`
`<html xmlns="http://www.w3.org/1999/xhtml">`
`<head>`
`<meta name="HandheldFriendly" content="True" />`
`<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>`
`<link rel="canonical" href="https://twitter.com">`
`<meta name="twitter-redirect-url" content="twitter://timeline"/>`
`<meta name="twitter-redirect-srcs" content="{&quot;pwreset-iphone&quot;:true,&quot;android&quot;:true,&quot;email&quot;:true}"/>`
`<link href="https://ma.twimg.com/twitter-mobile/0d...0e/images/favicon.ico" rel="icon" type="image/x-icon" />`
`<title>Twitter</title>`
`<link href="https://ma.twimg.com/twitter-mobile/0d...0e/assets/as.css" inline="false" media="screen" rel="stylesheet" type="text/css" />`
`<script src="https://ma.twimg.com/twitter-mobile/0d...0e/javascripts/framebust.js" type="text/javascript"></script>`
`<meta name="google-site-verification" content="V...w" />`
`</head>`

**Comment by whawker** [comment]
@TraderStf FYI you can do [multi line code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) by surrounding the block with three back ticks.

**Comment by TraderStf** [comment]
does not work... only see 3 first line then twitter only........

**Comment by joshbuchea** [comment]
@TraderStf this doesn't appear to be an actionable issue. Please keep issues limited to one element, or one set of elements per issue.
