### ISSUE TITLE
Order is important

### ISSUE THREAD

**Issue by silenceisgolden** [joshbuchea/HEAD#5]
I believe it is still best practice to get the charset and ie=edge tags in the first packet received by the browser. Could the order-dependent things like this be highlighted in a section?

**Comment by joshbuchea** [comment]
Excellent point. Absolutely, will add. Thanks @silenceisgolden!

**Comment by joshbuchea** [comment]
Oops didn't mean to close it yet.

**Comment by xc2** [comment]
Besides, a meta tag with attribute `charset`  must be within the 512 first bytes of the page.

[meta#attr-charset](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-charset)
