### ISSUE TITLE
Feel free to use

### ISSUE THREAD

**Issue by kevinSuttle** [joshbuchea/HEAD#61]
I used to keep a list of meta tags in the following gist. I believe you have most if not all, but if not, help yourself. 
https://gist.github.com/kevinSuttle/1997924

**Comment by joshbuchea** [comment]
@kevinSuttle I actually left you a comment on your gist a couple of weeks ago thanking you for your gist. It was one of the resources I used to compile the original version of this doc. Thanks for the great resource!

**Comment by kevinSuttle** [comment]
Awesome! Glad to help. Nice work here!
