### ISSUE TITLE
I thought meta-keywords was deprecated.

### ISSUE THREAD

**Issue by lewisje** [joshbuchea/HEAD#73]
At least I thought that all search engines had stopped using it in any way for years.

**Comment by JesseTG** [comment]
Oh, no, no, `<meta>` is alive and kicking,

**Comment by uppusaikiran** [comment]
The <meta> tag provides metadata about the HTML document. Metadata will not be displayed on the page, but will be machine parsable. Meta elements are typically used to specify page description, keywords, author of the document, last modified, and other metadata.Meta tags are snippets of text that describe a page's content; the meta tags don't appear on the page itself, but only in the page's code. We all know tags from blog culture, and meta tags are more or less the same thing, little content descriptors that help tell search engines what a web page is about.

**Comment by lode** [comment]
I think @lewisje means the `<meta name="keywords" ...` tag.

**Comment by uppusaikiran** [comment]
It helps in indexing the page while crawling for search engines @lode

**Comment by lode** [comment]
As far as I know (but note the topic was broad up by @lewisje - and I just guess at what he meant), search engines don't use the keywords anymore. Or if they do, to an almost negligible extend.

See https://webmasters.googleblog.com/2009/09/google-does-not-use-keywords-meta-tag.html and https://chrisedwards.me/seo/keyword-meta-tag-google/

I don't if that is enough reason to not include them in this repository though.

**Comment by lewisje** [comment]
Yes I was specifically talking about the `meta` tag with `name="keywords"` and upon re-reading the living standard, I find it's actually not deprecated; instead there's a note that says that search engines don't use it anymore because of problems with spam: https://html.spec.whatwg.org/multipage/semantics.html#meta-keywords

**Comment by uppusaikiran** [comment]
@lewisje  Thanks for letting know
