### ISSUE TITLE
Claim that meta robots is ignored by search engines

### ISSUE THREAD

**Issue by marakoss** [joshbuchea/HEAD#78]
Since when does search engines ignore robots in meta tags? I can provide statistical data that they follow it pretty strictly.

If you claim something is deprecated you should provide article that supports your statement and date since when it came to be.

Maybe you shouldn't use the word deprecated at all and just stick to something like: "I/we discourage to use".

Thank you

**Comment by joshbuchea** [comment]
@marakoss this was modified in a PR that I apparently didn't review close enough. You are absolutely correct. Will update. Also, going with your recommendation to be more conservative using the word **deprecated**.
