### ISSUE TITLE
meta name=robots is not deprecated

### ISSUE THREAD

**Issue by 4thana** [joshbuchea/HEAD#79]
AFAIK meta name=robots is still the preferred way to tell Google and other search engines to crawl and/or include a page in their index or not. It is also neither deprecated nor is it ignored by the crawlers. 

Your mentioned alternatives do something completely different. If you want to remove pages from the Google index for example it doesn't help to prevent the bot from accessing the pages (either via robots.txt or .htaccess), you will only prevent the pages from getting updated in this way, but they will still remain in the Google index forever. The only way to do this is via this meta tag (also recommended by Google: https://support.google.com/webmasters/answer/93710?hl=en).

Where exactly did you get the idea that it is deprecated and ignored by bots?

**Comment by joshbuchea** [comment]
@4thana this was modified in a PR that I apparently didn't review close enough. You are absolutely correct. Will update.
