### ISSUE TITLE
<meta name="robots" content="noodp">

### ISSUE THREAD

**Issue by JamesJosephFinn** [joshbuchea/HEAD#81]
You should add:

`<meta name="robots" content="noodp">`

to turn off getting your meta description and other data from DMOZ, and other defunct directories.

**Comment by joshbuchea** [comment]
Closing. While the value you listed is legit, I don't intend to add every possible value for every tag in the document. Thanks @JamesJosephFinn I appreciate all contributions!

**Comment by joshbuchea** [comment]
On second thought, I'll add this. Thanks @JamesJosephFinn!
