### ISSUE TITLE
Meta tag keywords

### ISSUE THREAD

**Issue by emattiazzi** [joshbuchea/HEAD#90]
`<meta name="keywords" content="your,keywords,here,comma,separated,no,spaces">`

Seems that this meta is no longer used by search engines

**Comment by lode** [comment]
See https://github.com/joshbuchea/HEAD/issues/73

**Comment by dcondrey** [comment]
Google does not use the keywords meta tag any longer https://webmasters.googleblog.com/2009/09/google-does-not-use-keywords-meta-tag.html

**Comment by joshbuchea** [comment]
Got this updated. Thanks guys!
