### ISSUE TITLE
Dissuade <meta name="generator"....>

### ISSUE THREAD

**Issue by dandart** [joshbuchea/HEAD#91]
I have seen <meta name="generator"...> used before, is it not an anti-recommendation?

**Comment by joshbuchea** [comment]
@dandart could you please elaborate?

**Comment by dandart** [comment]
I've seen generator around before, mainly on old frontpage-related sites. I thought it ought to be featured since it exists, but dissuaded since it's not a standard and/or doesn't add anything.

**Comment by vonrac** [comment]
The W3C lists it as a possibility, and no top-ranking websites speak against it. That said, it's very close to useless.

**Comment by joshbuchea** [comment]
Got this added. Thanks @dandart!

**Comment by tomlutzenberger** [comment]
I think one reason, to **not recommend** meta-generator is security related.

Imagine someone running a website based on an old Typo3 or Wordpress Version.
You reveal something like `generator="Typo3 4.5" ` an actually invite hackers to tear down your site.
It's like putting a big sign in your front-yard, saying 

> "My door locks are from 1874!"

You wouldn't do that, would you?
Of course, there are many ways to find out what your site is based on. But why make it easy for the bad guys?

**Conclusion:**
It always depends on your site/project, but the less technical data you provide, the better.

**Comment by joshbuchea** [comment]
@tomlutzenberger I generally agree with you. However, generator is actively used by WordPress today, and [Hide the Version of WordPress to Improve Security, or NOT?](https://www.wpwhitesecurity.com/wordpress-security/hide-wordpress-version-does-it-matter/). Also, it is an [HTML5 standardized metadata name](https://www.w3.org/TR/html5/document-metadata.html#standard-metadata-names).

I think @vonrac nailed it with:

> The W3C lists it as a possibility, and no top-ranking websites speak against it. That said, it's very close to useless.

**Comment by joshbuchea** [comment]
All that said, that tag makes me cringe a little when I see it 😬

**Comment by tomlutzenberger** [comment]
Me too.
So... what are you gonna do? Leave it untouched? :confused: 

I just don't see any benefit using it.

**Comment by joshbuchea** [comment]
Until a top-ranking site speaks against, I think I should leave it where it is. I try to roll with the general web development consensus as much as possible. And there doesn't seem to be a strong consensus either way on this one.

Sorry homie I know this one bothers you. Just pretend it isn't there 😆 Or talk someone prominent into writing about why it shouldn't be used.

**Comment by tomlutzenberger** [comment]
Alright, I see your point.

 \*calls Sundar Pichai\* :phone: :laughing:
