### ISSUE TITLE
Move Apple created but now generic meta tags to their own section?

### ISSUE THREAD

**Issue by scunliffe** [joshbuchea/HEAD#94]
Thinks like the meta tag for not rendering phone numbers as links to call were presented by Apple for iOS etc. but they've been adopted by other vendors both within WebKit and outside. E.g. The phone number one above is also used by Microsoft Edge http://stackoverflow.com/a/31978712/6144

**Comment by joshbuchea** [comment]
Excellent point 👍 Thanks @scunliffe!
