### ISSUE TITLE
Add table of contents and back to top links at the end of each section

### ISSUE THREAD

**Issue by jordanbrauer** [joshbuchea/HEAD#97]
I feel that scrolling through this is a little much, especially as it evolves.
Would adding a 'navigation system' of sorts to the README be allowed? (Sorry, new to GitHub and not sure on the etiquette for making pull requests).

**Comment by tomlutzenberger** [comment]
I think this is a great idea, not only because h2 and h3 Header look quite similar.

Regarding pull requests:
- Make a fork of the repository
- Make your desired changes and commit + push
- In your forked Repo, click "New pull request"

Hope this helps :grin:

**Comment by joshbuchea** [comment]
@jordanbrauer apologies for not getting back to you sooner. Asking before implementing seems like good etiquette to me 👍 A table of contents at the top, with links to the various sections would excellent!

Maybe leave out the link to the top for each section though... Just to minimize the number of lines we're adding to the project.

**Comment by jordanbrauer** [comment]
@joshbuchea I hear ya' loud and clear! It would be pretty bloaty...

@tomlutzenberger Thanks, I will keep that in mind for the future! I just don't wanna offend anyone or step out of my bounds as a contributor.

**Comment by joshbuchea** [comment]
@jordanbrauer I think just being conscious of your etiquette as you are, is all anyone can realistically expect from a contributor. Thanks again for your contribution.
